name: build-website
channels:
  - conda-forge
dependencies:
  - sphinx
  - recommonmark
  - sphinx-markdown-tables
  - sphinxcontrib-bibtex
  - sphinx-panels
  - ablog
  - pydata-sphinx-theme
  - myst-parser
  - sphinx-jinja
